### ISSUE TITLE
 template-node-typescript  Code pattern error

### ISSUE THREAD

**Issue by balasgit** [ibm-garage-cloud/planning#217]
**Describe the bug**
Jenkins is not getting started as fails on Build step.

**To Reproduce**
https://github.com/IBM/template-node-typescript Create from this template and register via OCP 311

**Expected behavior**
Pipeline should complete

**Screenshots**
![image](https://user-images.githubusercontent.com/25986944/77806505-e92ea980-7052-11ea-92ed-2a62ce322905.png)

![image](https://user-images.githubusercontent.com/25986944/77806558-0b282c00-7053-11ea-85a3-cd87b76fc32f.png)

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [X ] Red Hat OpenShift Managed Services
- [ X] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MACOS
 - Browser [e.g. chrome, safari] Safari 
 - Version [e.g. 22] 62

**Additional context**
OpenShift Build dev-austin-codepattern/gsi-enablement-one.microservice-austin-cp4-1 from https://github.com/gsi-enablement-one/microservice-austin-cp4.git
Checking out git https://github.com/gsi-enablement-one/microservice-austin-cp4.git into /var/lib/jenkins/jobs/dev-austin-codepattern/jobs/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/workspace@script to read Jenkinsfile
using credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
Cloning the remote Git repository
Cloning repository https://github.com/gsi-enablement-one/microservice-austin-cp4.git
 > git init /var/lib/jenkins/jobs/dev-austin-codepattern/jobs/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/workspace@script # timeout=10
Fetching upstream changes from https://github.com/gsi-enablement-one/microservice-austin-cp4.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
 > git fetch --tags --progress https://github.com/gsi-enablement-one/microservice-austin-cp4.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/gsi-enablement-one/microservice-austin-cp4.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/gsi-enablement-one/microservice-austin-cp4.git # timeout=10
Fetching upstream changes from https://github.com/gsi-enablement-one/microservice-austin-cp4.git
using GIT_ASKPASS to set credentials dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
 > git fetch --tags --progress https://github.com/gsi-enablement-one/microservice-austin-cp4.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse origin/master^{commit} # timeout=10
Checking out Revision 4041c5f3a64ed5b78e3d963d3d0824c82fef7e5f (origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 4041c5f3a64ed5b78e3d963d3d0824c82fef7e5f
Commit message: "name change"
First time build. Skipping changelog.
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] echo
Job name: dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4
[Pipeline] echo
Secret name: gsi-enablement-one-microservice-austin-cp4
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
All nodes of label ‘a.dev-austin-codepattern-gsi-enablement-one.microservice-1’ are offline

**Comment by seansund** [comment]
Can you run it again and include the log from the jenkins pod? It looks like your build agent is failing to start. My guess is that it is related to your long project name

**Comment by balasgit** [comment]
**Jenkins POD Logs**

2020-03-30 14:46:33.417+0000 [id=341889]	INFO	i.f.j.o.BuildSyncRunListener#onDeleted: onDeleted job/dev-austin-codepattern/job/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/2/
2020-03-30 14:46:33.431+0000 [id=714050]	INFO	o.c.j.p.k.p.PodTemplateStepExecution$PodTemplateCallback#finished: Removing pod template a.dev-austin-codepattern-gsi-enablement-one.microservice-2-h7wd1 from cloud openshift
2020-03-30 14:46:33.486+0000 [id=714050]	WARNING	o.j.p.w.cps.CpsThreadGroup#propagateErrorToWorkflow: encountered error but could not pass it to the flow
java.io.FileNotFoundException: /var/lib/jenkins/jobs/dev-austin-codepattern/jobs/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/builds/2/atomic15939954599610987617.tmp (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.<init>(RiverWriter.java:106)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:521)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:499)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:486)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:410)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-30 14:46:33.486+0000 [id=714050]	WARNING	o.j.p.w.cps.CpsThreadGroup#saveProgramIfPossible: program state save failed
java.io.FileNotFoundException: /var/lib/jenkins/jobs/dev-austin-codepattern/jobs/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/builds/2/atomic15939954599610987617.tmp (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.<init>(RiverWriter.java:106)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:521)
Caused: java.io.IOException: Failed to persist /var/lib/jenkins/jobs/dev-austin-codepattern/jobs/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/builds/2/program.dat
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:537)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:499)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:486)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:410)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-30 14:46:33.493+0000 [id=703474]	INFO	o.j.p.workflow.job.WorkflowRun#finish: dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4 #2 completed: ABORTED
2020-03-30 14:46:33.547+0000 [id=703474]	INFO	i.f.j.o.BuildSyncRunListener#onCompleted: onCompleted job/dev-austin-codepattern/job/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/2/
2020-03-30 14:46:33.595+0000 [id=703474]	INFO	i.f.j.o.CredentialsUtils#getSourceCredentials: Retrieving SourceSecret for BuildConfig gsi-enablement-one.microservice-austin-cp4 in Namespace dev-austin-codepattern
2020-03-30 14:46:33.627+0000 [id=703474]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Updated credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5 from Secret NamespaceName{dev-austin-codepattern:gsi-enablement-one-sbm-austin-cp5} with revision: 8366660
2020-03-30 14:46:33.634+0000 [id=703474]	INFO	i.f.j.o.CredentialsUtils#updateSourceCredentials: Linking BuildConfig sourceSecret gsi-enablement-one-sbm-austin-cp5 to Jenkins Credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
2020-03-30 14:46:33.707+0000 [id=714177]	INFO	i.f.j.o.BuildSyncRunListener#onStarted: starting polling build job/dev-austin-codepattern/job/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/3/
2020-03-30 14:46:33.900+0000 [id=703474]	INFO	i.f.j.o.BuildSyncRunListener#onFinalized: onFinalized job/dev-austin-codepattern/job/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/2/
2020-03-30 14:46:35.296+0000 [id=714212]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #1,941 from /172.30.10.49:60824
2020-03-30 14:46:39.388+0000 [id=38]	INFO	o.c.j.p.k.KubernetesCloud#provision: Excess workload after pending Kubernetes agents: 1
2020-03-30 14:46:39.389+0000 [id=38]	INFO	o.c.j.p.k.KubernetesCloud#provision: Template for label a.dev-austin-codepattern-gsi-enablement-one.microservice-3: Kubernetes Pod Template
2020-03-30 14:46:39.420+0000 [id=38]	INFO	h.s.NodeProvisioner$StandardStrategyImpl#apply: Started provisioning Kubernetes Pod Template from openshift with 1 executors. Remaining excess workload: 0
2020-03-30 14:46:49.396+0000 [id=42]	INFO	hudson.slaves.NodeProvisioner#lambda$update$6: Kubernetes Pod Template provisioning successfully completed. We have now 3 computer(s)
2020-03-30 14:46:49.532+0000 [id=714245]	INFO	o.c.j.p.k.KubernetesLauncher#launch: Created Pod: dev-austin-codepattern/a.dev-austin-codepattern-gsi-enablement-one.microservice--cd250
2020-03-30 14:46:51.510+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#getSourceCredentials: Retrieving SourceSecret for BuildConfig gsi-enablement-one.angular-austin-cp2 in Namespace dev-austin-codepattern
2020-03-30 14:46:51.523+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Updated credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5 from Secret NamespaceName{dev-austin-codepattern:gsi-enablement-one-sbm-austin-cp5} with revision: 8366660
2020-03-30 14:46:51.526+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#updateSourceCredentials: Linking BuildConfig sourceSecret gsi-enablement-one-sbm-austin-cp5 to Jenkins Credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
2020-03-30 14:46:51.541+0000 [id=42]	INFO	i.f.j.openshiftsync.BuildWatcher#reconcileRunsAndBuilds: Reconciling job runs and builds
2020-03-30 14:46:51.541+0000 [id=42]	INFO	i.f.j.openshiftsync.BuildWatcher#reconcileRunsAndBuilds: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@14e1383[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.angular-austin-cp2] runs for BuildConfig dev-austin-codepattern/gsi-enablement-one.angular-austin-cp2
2020-03-30 14:46:51.569+0000 [id=42]	INFO	i.f.j.openshiftsync.BuildWatcher#reconcileRunsAndBuilds: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@165ea26[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.graphql-austin-cp3] runs for BuildConfig dev-austin-codepattern/gsi-enablement-one.graphql-austin-cp3
2020-03-30 14:46:51.572+0000 [id=45]	INFO	i.f.j.openshiftsync.JobProcessor#createOrUpdateJob: Updated job dev-austin-codepattern-gsi-enablement-one.angular-austin-cp2 from BuildConfig NamespaceName{dev-austin-codepattern:gsi-enablement-one.angular-austin-cp2} with revision: 8393606
2020-03-30 14:46:51.575+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#getSourceCredentials: Retrieving SourceSecret for BuildConfig gsi-enablement-one.graphql-austin-cp3 in Namespace dev-austin-codepattern
2020-03-30 14:46:51.587+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Updated credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5 from Secret NamespaceName{dev-austin-codepattern:gsi-enablement-one-sbm-austin-cp5} with revision: 8366660
2020-03-30 14:46:51.589+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#updateSourceCredentials: Linking BuildConfig sourceSecret gsi-enablement-one-sbm-austin-cp5 to Jenkins Credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
2020-03-30 14:46:51.594+0000 [id=42]	INFO	i.f.j.openshiftsync.BuildWatcher#reconcileRunsAndBuilds: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@c90eaf[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4] runs for BuildConfig dev-austin-codepattern/gsi-enablement-one.microservice-austin-cp4
2020-03-30 14:46:51.615+0000 [id=42]	INFO	i.f.j.openshiftsync.JenkinsUtils#deleteRun: Deleting run: dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4 #1
2020-03-30 14:46:51.617+0000 [id=42]	WARNING	o.j.p.w.cps.CpsFlowExecution#onLoad: Error initializing storage and loading nodes, will try to create placeholders for: CpsFlowExecution[Owner[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/1:dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4 #1]]
java.io.IOException: Tried to load head FlowNodes for execution Owner[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/1:dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4 #1] but FlowNode was not found in storage for head id:FlowNodeId 1:11
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:679)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:716)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:659)
	at com.cloudbees.workflow.rest.external.RunExt.create(RunExt.java:298)
	at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:211)
	at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.onDeleted(BuildSyncRunListener.java:182)
	at hudson.model.listeners.RunListener.fireDeleted(RunListener.java:269)
	at hudson.model.Run.delete(Run.java:1605)
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.deleteRun(JenkinsUtils.java:538)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.reconcileRunsAndBuilds(BuildWatcher.java:504)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.access$100(BuildWatcher.java:65)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:148)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:70)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-03-30 14:46:51.617+0000 [id=42]	INFO	o.j.p.w.cps.CpsFlowExecution#createPlaceholderNodes: Creating placeholder flownodes for execution: CpsFlowExecution[Owner[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/1:dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4 #1]]
2020-03-30 14:46:51.629+0000 [id=45]	INFO	i.f.j.openshiftsync.JobProcessor#createOrUpdateJob: Updated job dev-austin-codepattern-gsi-enablement-one.graphql-austin-cp3 from BuildConfig NamespaceName{dev-austin-codepattern:gsi-enablement-one.graphql-austin-cp3} with revision: 8392423
2020-03-30 14:46:51.631+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#getSourceCredentials: Retrieving SourceSecret for BuildConfig gsi-enablement-one.microservice-austin-cp4 in Namespace dev-austin-codepattern
2020-03-30 14:46:51.646+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Updated credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5 from Secret NamespaceName{dev-austin-codepattern:gsi-enablement-one-sbm-austin-cp5} with revision: 8366660
2020-03-30 14:46:51.647+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#updateSourceCredentials: Linking BuildConfig sourceSecret gsi-enablement-one-sbm-austin-cp5 to Jenkins Credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
2020-03-30 14:46:51.681+0000 [id=42]	INFO	i.f.j.o.BuildSyncRunListener#onDeleted: onDeleted job/dev-austin-codepattern/job/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4/1/
2020-03-30 14:46:51.688+0000 [id=45]	INFO	i.f.j.openshiftsync.JobProcessor#createOrUpdateJob: Updated job dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4 from BuildConfig NamespaceName{dev-austin-codepattern:gsi-enablement-one.microservice-austin-cp4} with revision: 9518028
2020-03-30 14:46:51.690+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#getSourceCredentials: Retrieving SourceSecret for BuildConfig gsi-enablement-one.react-austin-cp1 in Namespace dev-austin-codepattern
2020-03-30 14:46:51.706+0000 [id=42]	WARNING	j.model.lazy.LazyBuildMixIn#removeRun: org.jenkinsci.plugins.workflow.job.WorkflowJob@c90eaf[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4] did not contain dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.microservice-austin-cp4 #1 to begin with
2020-03-30 14:46:51.707+0000 [id=42]	INFO	i.f.j.openshiftsync.BuildWatcher#reconcileRunsAndBuilds: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@1d357f1[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.react-austin-cp1] runs for BuildConfig dev-austin-codepattern/gsi-enablement-one.react-austin-cp1
2020-03-30 14:46:51.713+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Updated credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5 from Secret NamespaceName{dev-austin-codepattern:gsi-enablement-one-sbm-austin-cp5} with revision: 8366660
2020-03-30 14:46:51.714+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#updateSourceCredentials: Linking BuildConfig sourceSecret gsi-enablement-one-sbm-austin-cp5 to Jenkins Credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
2020-03-30 14:46:51.742+0000 [id=42]	INFO	i.f.j.openshiftsync.BuildWatcher#reconcileRunsAndBuilds: Checking job org.jenkinsci.plugins.workflow.job.WorkflowJob@33a628[dev-austin-codepattern/dev-austin-codepattern-gsi-enablement-one.sbm-austin-cp5] runs for BuildConfig dev-austin-codepattern/gsi-enablement-one.sbm-austin-cp5
2020-03-30 14:46:51.750+0000 [id=45]	INFO	i.f.j.openshiftsync.JobProcessor#createOrUpdateJob: Updated job dev-austin-codepattern-gsi-enablement-one.react-austin-cp1 from BuildConfig NamespaceName{dev-austin-codepattern:gsi-enablement-one.react-austin-cp1} with revision: 8377163
2020-03-30 14:46:51.754+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#getSourceCredentials: Retrieving SourceSecret for BuildConfig gsi-enablement-one.sbm-austin-cp5 in Namespace dev-austin-codepattern
2020-03-30 14:46:51.766+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Updated credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5 from Secret NamespaceName{dev-austin-codepattern:gsi-enablement-one-sbm-austin-cp5} with revision: 8366660
2020-03-30 14:46:51.767+0000 [id=45]	INFO	i.f.j.o.CredentialsUtils#updateSourceCredentials: Linking BuildConfig sourceSecret gsi-enablement-one-sbm-austin-cp5 to Jenkins Credential dev-austin-codepattern-gsi-enablement-one-sbm-austin-cp5
2020-03-30 14:46:51.807+0000 [id=45]	INFO	i.f.j.openshiftsync.JobProcessor#createOrUpdateJob: Updated job dev-austin-codepattern-gsi-enablement-one.sbm-austin-cp5 from BuildConfig NamespaceName{dev-austin-codepattern:gsi-enablement-one.sbm-austin-cp5} with revision: 8370089
2020-03-30 14:46:58.998+0000 [id=714337]	INFO	h.TcpSlaveAgentListener$ConnectionHandler#run: Accepted JNLP4-connect connection #1,942 from /172.30.150.132:32900

**Comment by balasgit** [comment]
[jenkins-1-n69dk-jenkins(1).log](https://github.com/ibm-garage-cloud/planning/files/4403563/jenkins-1-n69dk-jenkins.1.log)

Here is the Jenkins logs downloaded from POD

**Comment by balasgit** [comment]
thanks for the hint on the long project which seems to be clue for this project.. It helped.

**Comment by balasgit** [comment]
Is there any fix from Jenkins to address this long project name ? Any workaround in addition to reduce long name ?

**Comment by seansund** [comment]
There is a fix in the garage-pipelines. Can you do an `igc enable`?
