### ISSUE TITLE
Tekton Pipeline Error - CodePattern(S)

### ISSUE THREAD

**Issue by balasgit** [ibm-garage-cloud/planning#275]
**Describe the bug**
   Tekton pipeline error during build step. 

**To Reproduce**
Fork the project, clone the code pattterns (any), create the namespace , register pipeline on new namespace
- Testing from Dev Branch
- Testing from Beta Version of Toolkit

**Expected behavior**
Pipeline should run e2e

**Screenshots**
![image](https://user-images.githubusercontent.com/25986944/78724958-1a7d6400-78f4-11ea-93ec-c9e51602dac3.png)

![image](https://user-images.githubusercontent.com/25986944/78724996-2a954380-78f4-11ea-8c63-f6d98707e948.png)

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [ X] Red Hat OpenShift Managed Services
- [ ] Jenkins
- [X ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**

**Additional context**
step-build
{"level":"info","ts":1586289923.6587362,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}

> node-sass@4.13.1 install /workspace/source/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-72_binding.node
Download complete
Binary saved to /workspace/source/node_modules/node-sass/vendor/linux-x64-72/binding.node
Caching binary to /tekton/home/.npm/node-sass/4.13.1/linux-x64-72_binding.node

> jsonpath@1.0.2 postinstall /workspace/source/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

> node-sass@4.13.1 postinstall /workspace/source/node_modules/node-sass
> node scripts/build.js

Binary found at /workspace/source/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine

> nodemon@1.19.4 postinstall /workspace/source/node_modules/nodemon
> node bin/postinstall || exit 0

[32mLove nodemon? You can now support the project via the open collective:[22m[39m
 > [96m[1mhttps://opencollective.com/nodemon/donate[0m

> template-node-angular@1.0.0 postinstall /workspace/source
> cd client && npm install

> node-sass@4.13.1 install /workspace/source/client/node_modules/node-sass
> node scripts/install.js

Cached binary found at /tekton/home/.npm/node-sass/4.13.1/linux-x64-72_binding.node

> core-js@3.6.0 postinstall /workspace/source/client/node_modules/@angular-devkit/build-angular/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m

> core-js@2.6.11 postinstall /workspace/source/client/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> node-sass@4.13.1 postinstall /workspace/source/client/node_modules/node-sass
> node scripts/build.js

Binary found at /workspace/source/client/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine
npm WARN The package @angular/cli is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1415 packages from 1071 contributors and audited 33615 packages in 58.02s

33 packages are looking for funding
  run `npm fund` for details

found 37 vulnerabilities (36 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 751 packages from 802 contributors and audited 3731 packages in 88.764s

4 packages are looking for funding
  run `npm fund` for details

found 24 vulnerabilities (16 low, 1 moderate, 6 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
/workspace/source/client /workspace/source
npm WARN @angular-devkit/build-angular@0.900.3 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.900.3 requires a peer of typescript@>=3.6 < 3.8 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.0.3 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.0.3 requires a peer of typescript@>=3.6 < 3.8 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN carbon-components-angular@2.49.10 requires a peer of carbon-components@^9.70.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package @angular/cli is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 33615 packages in 14.762s

33 packages are looking for funding
  run `npm fund` for details

found 37 vulnerabilities (36 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
/workspace/source

> template-node-angular@1.0.0 build /workspace/source
> cd client && npm run build

> template-node-angular@0.0.0 build /workspace/source/client
> ng build

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber.project (/workspace/source/client/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/workspace/source/client/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/workspace/source/client/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/workspace/source/client/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/workspace/source/client/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/workspace/source/client/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/workspace/source/client/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/workspace/source/client/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/workspace/source/client/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/workspace/source/client/node_modules/rxjs/internal/operators/switchMap.js:86:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! template-node-angular@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the template-node-angular@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tekton/home/.npm/_logs/2020-04-07T20_07_20_797Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! template-node-angular@1.0.0 build: `cd client && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the template-node-angular@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tekton/home/.npm/_logs/2020-04-07T20_07_20_817Z-debug.log

step-test
{"level":"info","ts":1586289924.4019496,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
2020/04/07 20:07:21 Skipping step because a previous step failed

step-publish-pact
{"level":"info","ts":1586289925.201951,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
2020/04/07 20:07:22 Skipping step because a previous step failed

step-verify-pact
{"level":"info","ts":1586289926.10831,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
2020/04/07 20:07:23 Skipping step because a previous step failed

step-sonar-scan
{"level":"info","ts":1586289926.8796835,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
2020/04/07 20:07:24 Skipping step because a previous step failed

**Comment by balasgit** [comment]
![image](https://user-images.githubusercontent.com/25986944/78725211-9d9eba00-78f4-11ea-9d58-47df340b8290.png)
