### ISSUE TITLE
Users cannot create projects, only admins can

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#423]
`oc sync {DEV_NAMESPACE} --dev` fails with a permission error when run by a member of the USER access group:
```
oc sync inventory --dev
Setting up namespace inventory and serviceAccount default
⠋ Creating namespace: inventoryError preparing namespace Error: projects.project.openshift.io is forbidden: User "IAM#devbob101@gmail.com" cannot create resource "projects" in API group "project.openshift.io" at the cluster scope
    at /Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/kubernetes-client/backends/request/client.js:231:25
```

I assume this also means that users also cannot create namespaces in a Kubernetes cluster.

**Comment by bwoolf1** [comment]
`terraform/scripts/rbac-roles.yaml` only lets ADMINs list/create/delete namespaces/projects. USERs need to be able to create too.

Users should also be able to delete their own projects, but not built-in projects like `tools`, but that will probably require a more sophisticated RBAC config than what we have now.

**Comment by bwoolf1** [comment]
https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/commit/0097de60d9a884d672da51cc7289b466a9f942e7 is lightly tested, but gets around a problem I'm blocked on.

Was:
```
oc sync inventory --dev
Setting up namespace inventory and serviceAccount default
⠋ Creating namespace: inventoryError preparing namespace Error: projects.project.openshift.io is forbidden: User "IAM#devbob101@gmail.com" cannot create resource "projects" in API group "project.openshift.io" at the cluster scope
    at /Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/kubernetes-client/backends/request/client.js:231:25
```

Now:
```
oc sync inventory --dev
Setting up namespace inventory and serviceAccount default
```

And the console shows that the project was indeed created.

**Comment by abalasu1** [comment]
Ran the rbac.sh script against the USER group. But still not able to create projects:

$ oc sync dev-ab2 --dev
Setting up namespace dev-ab2 and serviceAccount default
⠦ Creating namespace: dev-ab2Error preparing namespace Error: projects.project.openshift.io is forbidden: User "IAM#arfoot653@gmail.com" cannot create resource "projects" in API group "project.openshift.io" at the cluster scope
    at /usr/local/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/kubernetes-client/backends/request/client.js:231:25
    at Request._callback (/usr/local/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/kubernetes-client/backends/request/client.js:168:14)
    at Request.self.callback (/usr/local/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1223:12) {
  code: 403,
  statusCode: 403
}

**Comment by timroster** [comment]
This is probably being caused to changes in the IAM synced roles to OCP 4.x . Now, users that have a Service role of `Edit` to a cluster will be added by IAM to a clusterrolebinding.rbac resource named **ibm-edit** with mapping to the OCP **edit** Cluster Role (see: https://docs.openshift.com/container-platform/4.3/authentication/using-rbac.html ).

In order for a user with this cluster role binding to be able to create projects, they also need to be added to the Cluster Role **self-provisioner** . After the user is sync'd from IAM to OCP rbac, this can be accomplished with:

`oc adm policy add-cluster-role-to-user self-provisioner IAM#<ibmid>`

**Comment by seansund** [comment]
> This is probably being caused to changes in the IAM synced roles to OCP 4.x . Now, users that have a Service role of `Edit` to a cluster will be added by IAM to a clusterrolebinding.rbac resource named **ibm-edit** with mapping to the OCP **edit** Cluster Role (see: https://docs.openshift.com/container-platform/4.3/authentication/using-rbac.html ).
> 
> In order for a user with this cluster role binding to be able to create projects, they also need to be added to the Cluster Role **self-provisioner** . After the user is sync'd from IAM to OCP rbac, this can be accomplished with:
> 
> `oc adm policy add-cluster-role-to-user self-provisioner IAM#<ibmid>`

@timroster Are the IAM access groups not being created as Groups in the cluster anymore? I'm not seeing the `IAM#{ACCESS_GROUP}` entries in the cluster now.

Instead of adding the role to the individual users we should create a group (assuming the IAM groups aren't available anymore) and give the appropriate access to the group. Then we can add users to the group as they get added to the cluster.

Its looking like we might want to come up with a component that will add the user to the account, add them to the Git org, and add them to the correct group(s) in the cluster

**Comment by timroster** [comment]
@seansund for OpenShift managed on IBM Cloud, it does not appear that there is any propagation of IAM access groups to cluster Groups. Based off: https://cloud.ibm.com/docs/openshift?topic=openshift-access_reference#service . The IAM to OCP rbac propagation is at the user level (whether or not it comes from a service policy at the access group or individual level).

Probably a decision in the overall flow needs to be made first... Do users need to be able to create projects at will? If yes, then using group membership on OCP rbac could work. Either by group or individual cluster-role assignment, there is still the matter of initial sync between IAM and OCP rbac. Seems like there is work coming on this and it is in testing.
