### ISSUE TITLE
Errors when igc-nodejs-v1-23-0 builds template-node-typescript

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#438]
When the Tekton pipeline igc-nodejs-v1-23-0 builds the [template-node-typescript](https://github.com/IBM/template-node-typescript) template, the Build step of the Build stage shows two errors building the NPM runtime into the Docker container:
- TSLint has been deprecated in favor of ESLint.
- Could not find any Python installation to use

Plus warnings about several deprecated packages. Seems like the build should run more cleanly and not need to log errors.

Here's the complete log:
```
STEP-BUILD

{"level":"info","ts":1594064573.446799,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
STEP 1: FROM registry.access.redhat.com/ubi8/nodejs-12:1-36 AS builder
Getting image source signatures
Copying blob sha256:b5a4aba5fb838842849ccb5c253fcda2c0b8a9e3071b08366f22bbead6d10bc6
Copying blob sha256:befb03b11956169cf23096fc58081ca35034a6545fc37d63605bf0d200fe5eda
Copying blob sha256:256c5bafa6bf9f016e45e7814845a896cf22582174408182222d07c1b6129b49
Copying blob sha256:b6edece17e86ae59c1be4f7120079f9407e68444516fcc5ce757a9eb2d3af61d
Copying blob sha256:ee2244abc66ff9c6a4bf50fe19041fec82a95c87d18ee3a3660368cb274927c7
Copying config sha256:c2c2b09149eebb195926db68d8a20bea00983e789162a8d2b49462fbc9cf6865
Writing manifest to image destination
Storing signatures
STEP 2: WORKDIR /opt/app-root/src
STEP 3: COPY src src
STEP 4: COPY swagger.config.json .
STEP 5: COPY tsconfig.json .
STEP 6: COPY package.json .
STEP 7: RUN npm install
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.87.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> dtrace-provider@0.8.8 install /opt/app-root/src/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Linux 3.10.0-1127.10.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/app-root/src/node_modules/dtrace-provider
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> core-js@2.6.11 postinstall /opt/app-root/src/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> core-js@3.6.5 postinstall /opt/app-root/src/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall /opt/app-root/src/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> @pact-foundation/pact-node@10.9.6 postinstall /opt/app-root/src/node_modules/@pact-foundation/pact-node
> node postinstall.js

Installing Pact Standalone Binary for linux.
Downloading Pact Standalone Binary v1.85.0 for platform linux from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.85.0/pact-1.85.0-linux-x86_64.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
Finished downloading binary to /opt/app-root/src/node_modules/@pact-foundation/pact-node/standalone/pact-1.85.0-linux-x86_64.tar.gz
Extracting binary from /opt/app-root/src/node_modules/@pact-foundation/pact-node/standalone/pact-1.85.0-linux-x86_64.tar.gz.
Checksum passed for 'pact-1.85.0-linux-x86_64.tar.gz'.
Extraction done.


### If you ❤ Pact and want to support us, please donate here: http://donate.pact.io/node


Pact Standalone Binary is ready.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1462 packages from 785 contributors and audited 1473 packages in 65.802s

25 packages are looking for funding
  run `npm fund` for details

found 4707 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
STEP 8: RUN npm run build

> stockbffnode-bw@1.0.0 prebuild /opt/app-root/src
> npm run clean


> stockbffnode-bw@1.0.0 clean /opt/app-root/src
> rimraf dist


> stockbffnode-bw@1.0.0 build /opt/app-root/src
> tsc


> stockbffnode-bw@1.0.0 postbuild /opt/app-root/src
> npm run swagger


> stockbffnode-bw@1.0.0 swagger /opt/app-root/src
> swaggerGen -c ./swagger.config.json

Generation completed.
STEP 9: FROM registry.access.redhat.com/ubi8/nodejs-12:1-36
STEP 10: COPY --from=builder /opt/app-root/src/dist dist
STEP 11: COPY public public
STEP 12: COPY package.json .
STEP 13: RUN npm install --production
npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.87.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> core-js@3.6.5 postinstall /opt/app-root/src/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m


> core-js-pure@3.6.5 postinstall /opt/app-root/src/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 327 packages from 260 contributors and audited 1473 packages in 40.065s

10 packages are looking for funding
  run `npm fund` for details

found 4707 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
STEP 14: ENV HOST=0.0.0.0 PORT=3000
STEP 15: EXPOSE 3000/tcp
STEP 16: CMD npm run serve
STEP 17: COMMIT us.icr.io/sandbox-team-one-isv/stockbffnode-bw:0.0.1
Getting image source signatures
Copying blob sha256:d3ada5af5602bd0da378e4f0144f8fe8bdbe3f5a65f367dd9ebe759756bada68
Copying blob sha256:668db11eda933a46ae8030a8643b96088218dae0efeac54bc6dbc88488725c1b
Copying blob sha256:a125291fda03bea387476e19d4d21b1c0714a7038f250f28dbd2f659d5f03423
Copying blob sha256:fa5e53639e9de7619687116de1eac523976d16e038bb2f74024e7d58b026e263
Copying blob sha256:bdf63d2e486370bec5a14771dbe8824e4b1dc042f5f12ee00f4cdaa5a699efbc
Copying blob sha256:11b3d7c5d0af05222cf85f0e634f41c6c19071634d7831d94d86775cb9d91f72
Copying config sha256:4db2f693a551421eac3b51e787c53d2c6141319557669385e767b4e236030623
Writing manifest to image destination
Storing signatures
4db2f693a551421eac3b51e787c53d2c6141319557669385e767b4e236030623
Login Succeeded!
Getting image source signatures
Copying blob sha256:a125291fda03bea387476e19d4d21b1c0714a7038f250f28dbd2f659d5f03423
Copying blob sha256:d3ada5af5602bd0da378e4f0144f8fe8bdbe3f5a65f367dd9ebe759756bada68
Copying blob sha256:668db11eda933a46ae8030a8643b96088218dae0efeac54bc6dbc88488725c1b
Copying blob sha256:11b3d7c5d0af05222cf85f0e634f41c6c19071634d7831d94d86775cb9d91f72
Copying blob sha256:fa5e53639e9de7619687116de1eac523976d16e038bb2f74024e7d58b026e263
Copying blob sha256:bdf63d2e486370bec5a14771dbe8824e4b1dc042f5f12ee00f4cdaa5a699efbc
Copying config sha256:4db2f693a551421eac3b51e787c53d2c6141319557669385e767b4e236030623
Writing manifest to image destination
Storing signatures
```

**Comment by bwoolf1** [comment]
The stage and pipeline still complete successfully and deploy the app. So these errors don't break the build, but they do warn of issues and make the logs look ugly.

**Comment by bwoolf1** [comment]
Python error in template-graphql-typescript as well. Deprecated packages in that and template-node-angular.
