### ISSUE TITLE
Pipeline command error: It appears the kubernetes environment has not been initialized.

### ISSUE THREAD

**Issue by bwoolf1** [ibm-garage-cloud/planning#455]
When I ran the `igc pipeline` command, it gave an error, "It appears the kubernetes environment has not been initialized." When I selected Tekton, I got a stackdump starting from `.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/dist/util/kubernetes.js:31:23`.

This environment was created more than a week ago and worked fine on Friday, but started failing on Saturday. What's changed? How does it break existing environments that were already working?

Here's the terminal output of running `pipeline`:
```
➜  hello-test-spring-bw git:(master) oc pipeline
It appears the kubernetes environment has not been initialized.
To initialize kubernetes:
 1) Navigate to https://cloud.ibm.com/kubernetes/clusters
 2) Select the kubernetes cluster with which to work
 3) Follow the instructions on the access tab

? Select the type of pipeline that should be run? 
  Jenkins 
❯ Tekton 
/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/dist/util/kubernetes.js:31
                throw new Error('Kubernetes not set');
                ^

Error: Kubernetes not set
    at Interface.<anonymous> (/Users/bwoolf/.npm/lib/node_modules/@ibmgaragecloud/cloud-native-toolkit-cli/dist/util/kubernetes.js:31:23)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at ReadStream.ondata (readline.js:186:10)
    at ReadStream.emit (events.js:327:22)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at ReadStream.Readable.push (_stream_readable.js:212:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by bwoolf1** [comment]
My mistake. Please ignore.
